### ISSUE TITLE
The specified bucket does not exist error message

### ISSUE THREAD

**Issue by dohomi** [k1LoW/serverless-s3-sync#14]
Hello,

I'd like to try this plugin but after initial yml setup I receive following error message:
  The specified bucket does not exist
Does this package handle the creation/update of a folder somehow? I guess some BucketPolicy is missing but the README does not mention it. I'm new to serverless would be great to find some resource here

**Comment by jpetitcolas** [comment]
I also had something similar:

```
serverless deploy --stage staging
Serverless: Packaging service...

  Serverless Error ---------------------------------------

  The specified bucket does not exist

  Get Support --------------------------------------------
     Docs:          docs.serverless.com
     Bugs:          github.com/serverless/serverless/issues
     Issues:        forum.serverless.com
```

The reason was that I deleted a weird serverless S3 bucket, with a name such as `mybucketname-staging-serverlessdeploymentbucket-xxxxx`. But apparently, `serverless` uses this as a kind of referential to store its configuration (didn't find any documentation in regards to this specific bucket). 

The solution is to relaunch a `serverless create` command.

**Comment by jpetitcolas** [comment]
And you may also have to remove the created CloudFormations: https://console.aws.amazon.com/cloudformation/home?region=us-east-1#/stacks?filter=active

**Comment by nibynool** [comment]
@dohomi has this issue been resolved?  If so, could you perhaps close it? :)

**Comment by dohomi** [comment]
@nibynool I moved to different approach will close this one
