### ISSUE TITLE
Cache-Control headers not updated if files have not changed.

### ISSUE THREAD

**Issue by jannylund** [k1LoW/serverless-s3-sync#35]
If you first sync a folder via s3sync, then edit the metadata via params, the changes are not reflected in S3. Solution is to delete file manually from S3 and it will get the proper settings on next run.

On first run I had:
```custom:
  hostName: <REDACTED>
  s3Sync:
    - bucketName: ${self:custom.hostName}
      localDir: static
      defaultContentType: text/html
```

Then to disable cache, I updated to:
```custom:
  hostName: <REDACTED>
  s3Sync:
    - bucketName: ${self:custom.hostName}
      localDir: static
      defaultContentType: text/html
      params:
        - 'index.html':
          CacheControl: 'no-cache'
```

EDIT: This seems to also be the behavior of calling `aws s3 sync...` and passing a cache-control parameter. Unless file is modified, the cache is not reflected in s3.

**Comment by trilom** [comment]
## The Problem  

I've done a fair bit of research into this and trying to come up with a reasonable solution.  

The bottom line of what is happening here is that this plugin is using the `@auth0/s3` repository for the S3 interactions.  This isn't the problem but the problem is that this plugin uses the `uploadDir(params)` function of this repository.  This function's underlying S3 call is [putObject](https://docs.aws.amazon.com/AWSJavaScriptSDK/latest/AWS/S3.html#putObject-property).   

The great thing about the `@auth0/s3.uploadDir(params)` function is that it will calculate the MD5 sums of each file locally, and compare it to the files in S3.  If there are differences then it will do a brand new `putObject(params)` which will grab the current metadata in the `custom.s3Sync.params` section of your *serverless.yml*.  If the file hasn't changed, then the MD5 sum has also not changed, therefor the `@auth0/s3.uploadDir(params)` will not upload anything.  Hopefully this encapsulates the problem.  

## Recreation
```serverless.yml
service: trailmix-testbuck
provider:
  name: aws
  runtime: python3.6
  region: us-west-2
  log_level: DEBUG
  memorySize: 512
  logRetentionInDays: 30
  versionFunctions: false

custom:
  S3webBucket: trailmix-testbuck
  s3Sync:
    - bucketName: ${self:custom.S3webBucket}
      localDir: public/
      params: ${file(s3.params.json):params}

plugins:
  - serverless-s3-sync

resources:
  Resources:
    S3Bucket:
      Type: AWS::S3::Bucket
      DeletionPolicy: Delete
      Properties:
        BucketName: ${self:custom.S3webBucket}
        AccessControl: PublicRead
        WebsiteConfiguration:
          IndexDocument: index.html
          ErrorDocument: 404.html
        CorsConfiguration:
          CorsRules:
          - Id: AllowAllRule
            AllowedHeaders: ['*']
            AllowedMethods: [GET]
            AllowedOrigins: ['*']
            MaxAge: '3600'
```
```s3.params.json
{
  "params": [
    { "sw.js": { "CacheControl": "public, max-age=1024, must-revalidate" } },
    { "test.js": { "CacheControl": "public, max-age=3002, must-revalidate" } },
    { "test2.js": { "CacheControl": "public, max-age=3001, must-revalidate" } }
  ]
}
```
``` tree
❯ tree
.
├── package.json
├── public
│   ├── sw.js
│   ├── test.js
│   ├── test2.js
│   └── test3.js
├── s3.params.json
├── serverless.yaml
└── yarn.lock
```
Within public you should have some test files that match your *s3.params.json* in order to see if the metadata changes persist.  After having this setup simply run `sls deploy` and after the deployment is successful you should be able to validate that the CacheControl parameters have been sit in the metadata.  

## Possible Solutions . 

Within the *index.js* of `serverless-s3-sync` we need to find some way to set aside those which have metadata changes versus those which do not.  And if there is a metadata change then within the getS3Params we could potentially do a `@auth0/s3.copyObject(params)` call with adding `MetadataDirection: 'REPLACE'` to the params.  Then after a successful upload, we can return a `callback(err, null` from the `getS3Params` function so that the file doesn't get a `putObject(params)` call from the AWS-SDK.  There obviously might be a better way to handle what files need to be sorted out for `copyObject` versus `putObject` instead of putting it in the `getS3Params` function.  Aside from this the only problem seems to be identifying changes to the metadata, and knowing which files need to change.  I've bounced around ideas in my head of how to do this and the best that I am coming up with is doing similar to what `@auth0/s3` does and checking on the MD5 of the `s3.params.json` file, or the `serverless.yml` file (bonus points if it can focus specifically on `custom.s3Sync.params` to see if any have changed.  I've considered where to store this information, in the bucket in a file, but don't like adding to people's work like this.  Another idea I had from [here](https://stackoverflow.com/a/37858374) was basically to add a header with the MD5/file info I want.  Then every time `uploadDir(params)` occurs it will check the header or bucket file MD5 of the Metadata information and then run a special `copyObject(params)` for each file.

I don't have any real work to apply, just the research I've done into the problem and what I think might be possible solutions.  If you want to help guide a solution you think might fit that I might not be able to see, or that you might know/see clearer than I please let me know and I can implement as needed.

Thanks!
